os:
  - linux

language: python

python:
    - 3.7

sudo: required
        
branches:
    - master
    - /^v.*$/
    - develop

# Builds Test

env: 
    - PLATFORMIO_CI_SRC=examples/high-side-switch
    - PLATFORMIO_CI_SRC=examples/high-side-switch

install: 
  - pip install -U platformio==4.1.0
  - platformio platform install -f infineonxmc@1.1.3 
  - platformio platform install -f atmelavr@2.0.0

script: 
  - platformio ci --lib="." --board=xmc1100_boot_kit --board=xmc4700_relax_kit --board=uno

jobs:
  include:   
    - stage: "Deploy" 
      name: "GitHub Pages Deployment"
      #if: tag IS present
      addons:
        apt:
            packages:
            - doxygen
            - graphviz
            sources:
                - ubuntu-toolchain-r-test
      install:
        - git clone https://github.com/Infineon/InfineonDoxyGenerator.git --branch v.0.2.1
      script: 
        - cd InfineonDoxyGenerator
        - python doxyifx.py html
        - python doxyifx.py release $GH_USER $GH_PASS_TOKEN